name: Laravel CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Cache Composer Dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Dependencies
      run: |
        composer install --quiet --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Directory Permissions
      run: chmod -R 775 storage bootstrap/cache

    - name: FTP Deploy to Staging
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 62.72.28.24
        username: u919013155
        password: =n>YX8zL&?V0hdA0
        serverPort: 21
        localDir: ./  # Path to your local directory to deploy
        remoteDir: /domains/mohitrana.com/public_html/library/  # Remote directory to deploy to
        exclude: |
          vendor
          .env
          node_modules
          tests
          .git

    - name: Run php artisan storage:link
      run: php artisan storage:link
